"""create sections

Revision ID: 8dcc61ada1e1
Revises: 3083d90504be
Create Date: 2023-07-17 17:39:10.346824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dcc61ada1e1'
down_revision = '3083d90504be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.Text(), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_images', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('post')

    # ### end Alembic commands ###


def downgrade():
    # # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('posts', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('post', sa.TEXT(), nullable=False))

    with op.batch_alter_table('post_images', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    op.drop_table('sections')
    # ### end Alembic commands ###
