# """create all tables

# Revision ID: 3083d90504be
# Revises: ffdc0a98111c
# Create Date: 2023-07-13 09:18:38.304375

# """
# from alembic import op
# import sqlalchemy as sa

# import os
# environment = os.getenv("FLASK_ENV")
# SCHEMA = os.environ.get("SCHEMA")


# # revision identifiers, used by Alembic.
# revision = '3083d90504be'
# down_revision = 'ffdc0a98111c'
# branch_labels = None
# depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('posts',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('owner_id', sa.Integer(), nullable=False),
#     sa.Column('title', sa.Text(), nullable=False),
#     sa.Column('heading', sa.Text(), nullable=False),
#     sa.Column('post', sa.Text(), nullable=False),
#     sa.Column('created_at', sa.DateTime(), nullable=False),
#     sa.Column('updated_at', sa.DateTime(), nullable=False),
#     sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
#     sa.PrimaryKeyConstraint('id')
#     )

#     if environment == "production":
#         op.execute(f"ALTER TABLE posts SET SCHEMA {SCHEMA};")

#     op.create_table('comments',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('user_id', sa.Integer(), nullable=False),
#     sa.Column('comment', sa.Text(), nullable=False),
#     sa.Column('post_id', sa.Integer(), nullable=False),
#     sa.Column('created_at', sa.DateTime(), nullable=False),
#     sa.Column('updated_at', sa.DateTime(), nullable=False),
#     sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
#     sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
#     sa.PrimaryKeyConstraint('id')
#     )

#     if environment == "production":
#         op.execute(f"ALTER TABLE comments SET SCHEMA {SCHEMA};")

#     op.create_table('post_images',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('post_id', sa.Integer(), nullable=False),
#     sa.Column('image', sa.String(), nullable=False),
#     sa.Column('created_at', sa.DateTime(), nullable=False),
#     sa.Column('updated_at', sa.DateTime(), nullable=False),
#     sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
#     sa.PrimaryKeyConstraint('id')
#     )

#     if environment == "production":
#         op.execute(f"ALTER TABLE post_images SET SCHEMA {SCHEMA};")

#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###

#     op.drop_table('post_images')
#     op.drop_table('comments')
#     op.drop_table('posts')
#     # ### end Alembic commands ###
