"""update posts and sections

Revision ID: 7fbc0ec290bf
Revises: 8dcc61ada1e1
Create Date: 2023-07-17 18:56:42.998380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fbc0ec290bf'
down_revision = '8dcc61ada1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_heading', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_column('section_heading')

    # ### end Alembic commands ###
